server:
  port: 8081

spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hmdp?rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    username: root
    password: 1234
  redis:
    host: 127.0.0.1
    port: 6379
    password: 1234
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: "/"
    username: guest
    password: guest
    listener:
      simple:
        prefetch: 1                   # 按需取
        acknowledge-mode: auto        # 自动模式(根据侦听器检测是正常返回、还是抛出异常来发出 ack/nack)
        retry:
          enabled: true
          initial-interval: 1000
          multiplier: 2               # 重试时间为x^n，x为这里的值，n为重试次数
          max-attempts: 4
          stateless: true             # 消息事务，消息之间是原子的，必须一起成功或失败执行
    publisher-confirm-type: correlated # 异步回调，有返回结果时调用confirmCallback
    publisher-returns: true            # 开启publisher-returns，有返回结果时调用returnCallback
    template:
      mandatory: true                  # 失败返回returnCallback，false的话会直接丢弃



  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段

mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包

logging:
  level:
    com.hmdp: info
#    com.hmdp: debug
